# Generated by Django 3.0.8 on 2021-05-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='university full name')),
                ('university_type', models.CharField(choices=[('PUBLIC', 'A public university'), ('PRIVATE', 'A private university')], max_length=12, verbose_name='type of university')),
            ],
        ),
    ]
