# Generated by Django 3.0.8 on 2021-05-02 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_university'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='university_type',
            new_name='university',
        ),
    ]
