# Generated by Django 3.0.8 on 2021-05-02 11:24

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20210501_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='country',
            field=django_countries.fields.CountryField(default='congo', max_length=2),
            preserve_default=False,
        ),
    ]
