# Generated by Django 3.0.8 on 2021-05-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_billingaddress_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-amount'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payment'},
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['amount'], name='shop_paymen_amount_e2e3ba_idx'),
        ),
    ]
